name: good-mood
channels:
  - pytorch
  - conda-forge
dependencies:
  - aiofiles=23.1.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - altair=5.0.1
  - annotated-types=0.5.0
  - anyio=3.7.1
  - aom=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=23.1.0
  - audioread=3.0.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - black=23.7.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.6
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.1.4
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.6.8
  - decorator=5.1.1
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - expat=2.5.0
  - fastapi=0.101.0
  - ffmpeg=6.0.0
  - ffmpy=0.3.0
  - filelock=3.12.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - gettext=0.21.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - gradio=3.23.0
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=7.3.0
  - hpack=4.0.0
  - httpcore=0.17.3
  - httpx=0.24.1
  - huggingface_hub=0.16.4
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.4
  - imageio=2.31.1
  - imageio-ffmpeg=0.4.8
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.1
  - ipython=8.14.0
  - isort=5.12.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - kiwisolver=1.4.4
  - lame=3.100
  - lazy_loader=0.2
  - lcms2=2.15
  - lerc=4.0.0
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgfortran=5.0.0
  - libgfortran5=12.3.0
  - libglib=2.76.4
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - librosa=0.10.0
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.13.0
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - llvm-openmp=16.0.6
  - llvmlite=0.40.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.3
  - mdurl=0.1.0
  - moviepy=1.0.3
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpg123=1.31.3
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=3.1
  - numba=0.57.1
  - numpy=1.24.4
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.2
  - orjson=3.9.3
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pathlib=1.0.1
  - pathspec=0.11.2
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.15.0
  - pooch=1.6.0
  - proglog=0.1.9
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=2.1.1
  - pydantic-core=2.4.0
  - pydub=0.25.1
  - pygments=2.16.1
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-multipart=0.0.6
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.0.1
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.1.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rpds-py=0.9.2
  - ruff=0.0.284
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - semantic_version=2.10.0
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.3.0
  - soxr=0.1.3
  - soxr-python=0.3.5
  - stack_data=0.6.2
  - starlette=0.27.0
  - svt-av1=1.6.0
  - sympy=1.12
  - tenacity=8.2.2
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - torchvision=0.15.2
  - tornado=6.3.2
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - unicodedata2=15.0.0
  - urllib3=2.0.4
  - uvicorn=0.23.2
  - wcwidth=0.2.6
  - websockets=11.0.3
  - wheel=0.41.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
